# Generated by Django 4.2.2 on 2023-06-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime',
            new_name='publish',
        ),
    ]
